### ISSUE TITLE
Progress Dots not Showing Jasmine 2.6.1

### ISSUE THREAD

**Issue by globehealer-developer** [jasmine/gulp-jasmine-browser#48] opened 2017-04-28 15:52 UTC
Hi, in Jasmine-Core 2.6.1, when we run our jasmine suite on the browser, the progress dots are no longer showing on Chrome/Safari, but they do show up on Firefox. Our tests are all running just fine, it's just the progress dots not showing.

I'm not sure how or why this is happening but here's some snippets.

```javascript
var jasmineBrowser = require('gulp-jasmine-browser');
var JasminePlugin = require('gulp-jasmine-browser/webpack/jasmine-plugin');

function sharedJasmineSetup(opts) {
  opts = opts || {};
  const stopOnSyntaxErrors = !!opts.stopOnSyntaxErrors,
    watch = !!opts.watch;

  const jasminePlugin = new JasminePlugin();
  const stopBuildOnFailurePlugin = function() {
    this.plugin('done', function(webpackResult) {
      if (webpackResult.compilation.errors && webpackResult.compilation.errors.length) {
        console.log('There are compilation problems.', webpackResult.compilation.errors.map(error => error.message));
        process.exit(1)
      }
    })
  };

  var plugins = [jasminePlugin];
  if (stopOnSyntaxErrors) {
    plugins.push(stopBuildOnFailurePlugin);
  }

  return gulp.src([paths.js.es5Shim, paths.js.spec])
    .pipe(plumber())
    .pipe(webpack_stream({
      watch: watch,
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel-loader'
          },
          {
            include: /\.json$/,
            loaders: ["json-loader"]
          }
        ]
      },
      devtool: "#inline-source-map",
      output: {
        filename: 'spec.js'
      },
      plugins: plugins
  }

gulp.task('jasmine', function () {
  return sharedJasmineSetup({watch: true})
    .pipe(jasmineBrowser.specRunner())
    .pipe(jasmineBrowser.server());
});
```

What the browser looks like:
<img width="1282" alt="screen shot 2017-04-28 at 11 50 30 am" src="https://cloud.githubusercontent.com/assets/19353484/25536480/ff250176-2c08-11e7-8fc2-f55cfd56921a.png">

Package.json

```
{
  "name": "globehealer",
  "version": "1.0.0",
  "description": "# LicenseFinder",
  "main": "index.js",
  "directories": {
    "doc": "doc"
  },
  "devDependencies": {
    "babel-core": "6.x",
    "babel-eslint": "6.x",
    "babel-loader": "5.x",
    "babel-plugin-transform-es2015-modules-umd": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-runtime": "6.x",
    "es5-shim": "4.x",
    "eslint": "2.x",
    "gulp": "3.x",
    "gulp-chmod": "1.x",
    "gulp-eslint": "2.x",
    "gulp-jasmine-browser": "1.x",
    "gulp-livereload": "3.x",
    "gulp-plumber": "1.x",
    "gulp-rename": "1.x",
    "gulp-replace": "0.x",
    "gulp-sass": "2.x",
    "gulp-shell": "0.x",
    "jasmine-ajax": "3.x",
    "jasmine_dom_matchers": "1.x",
    "js-cookie": "2.1.x",
    "karma": "^1.6.0",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-firefox-launcher": "^1.0.1",
    "karma-html-live-reporter": "^0.1.5",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-phantomjs2-launcher": "^0.5.0",
    "karma-safari-launcher": "^1.0.0",
    "karma-webpack-preprocessor": "^1.0.1",
    "react-addons-perf": "0.14.x",
    "react-addons-pure-render-mixin": "0.14.x",
    "react-addons-test-utils": "0.14.x",
    "react-md-spinner": "^0.2.1",
    "webpack": "1.x",
    "webpack-stream": "3.x"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.18.0",
    "blueimp-file-upload": "^9.14.2",
    "bootstrap-sass": "3.3.x",
    "chart.js": "^2.4.0",
    "chartkick": "^2.2.1",
    "classnames": "2.2.x",
    "crypto": "0.0.3",
    "email-validator": "1.x",
    "es6-promise": "3.x",
    "exif-js": "2.1.x",
    "faye": "^1.2.3",
    "font-awesome": "4.x",
    "formsy-react": "0.18.x",
    "google-map-react": "0.13.x",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.6.1",
    "gulp-sass-glob": "1.x",
    "gulp-sourcemaps": "1.x",
    "history": "1.17.x",
    "i18n-js": "1.x",
    "immutable": "3.x",
    "j-toker": "~0.0.10-beta3",
    "jquery": "2.x",
    "jquery-ui": "^1.12.1",
    "jquery-ujs": "1.x",
    "json-loader": "^0.5.4",
    "moment": "2.x",
    "moment-timezone": "^0.5.11",
    "node-notifier": "4.x",
    "numeral": "1.x",
    "postscribe": "2.0.x",
    "pui-css-buttons": "3.x",
    "pui-css-dividers": "3.x",
    "pui-css-dropdowns": "3.x",
    "pui-css-grids": "3.x",
    "pui-css-variables-and-mixins": "4.x",
    "pui-css-whitespace": "3.x",
    "pui-react-buttons": "3.x",
    "pui-react-dividers": "3.x",
    "pui-react-dropdowns": "3.x",
    "pui-react-grids": "3.x",
    "rc-calendar": "5.5.x",
    "rc-collapse": "1.6.x",
    "rc-slider": "3.7.x",
    "rc-steps": "2.1.x",
    "rc-tree": "^1.4.3",
    "react": "0.14.x",
    "react-addons-update": "0.14.x",
    "react-bootstrap": "0.30.x",
    "react-bootstrap-table": "2.x",
    "react-chartkick": "^0.1.3",
    "react-cookie": "0.4.x",
    "react-datepicker": "^0.41.1",
    "react-dom": "0.14.x",
    "react-flipcard": "0.2.x",
    "react-motion-drawer": "3.0.x",
    "react-popover": "0.4.x",
    "react-redux": "4.4.x",
    "react-router": "2.0.x",
    "react-select": "~1.0.0-beta13",
    "react-slick": "0.13.x",
    "react-widgets": "3.4.x",
    "redux": "3.5.x",
    "rosie": "1.x",
    "seamless-immutable": "6.1.x",
    "setimmediate": "1.0.x",
    "shallow-equals": "0.0.x",
    "typeahead.js-browserify": "1.0.x"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/globehealer/globehealer.git"
  },
  "author": "",
  "license": "UNLICENSED",
  "bugs": {
    "url": "https://github.com/globehealer/globehealer/issues"
  },
  "homepage": "https://github.com/globehealer/globehealer#readme"
}

```

Any help would be appreciated! :)

**Comment by rdy** [comment] 2017-05-25 21:54
Looks like this was introduced in jasmine 2.6.x we will lock down to an older jasmine until the issue can be resolved.

**Comment by globehealer-developer** [comment] 2017-05-30 16:26
Thanks for reopening this @rdy, Not sure why @sgravrock closed it.

**Comment by slackersoft** [comment] 2017-06-07 21:10
We believe this should be fixed with the 2.6.3 release of jasmine-core, but the only reproduction steps we were able to find was when async specs called `done` synchronously, so it may not fix all users.

**Comment by globehealer-developer** [comment] 2017-06-08 15:28
Ok will give it a try!

**Comment by globehealer-developer** [comment] 2017-06-08 15:35
It works! Thanks guys, upgrading to jasmine-core 2.6.3 fixed it.

**Closed** 2017-06-15 21:30 UTC
